# Generated by Django 5.0.2 on 2026-04-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_add_audio"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="link_previews",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
