# Generated by Django 5.0.2 on 2026-04-11 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0008_add_folder_and_archived"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="folder",
            new_name="folders_user_id_714bf9_idx",
            old_name="folders_user_archived_idx",
        ),
        migrations.RenameIndex(
            model_name="note",
            new_name="notes_user_id_ff3b91_idx",
            old_name="notes_user_archived_idx",
        ),
    ]
