# Generated by Django 5.0.2 on 2026-04-11 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0009_rename_folders_user_archived_idx_folders_user_id_714bf9_idx_and_more"),
        ("notes", "0010_add_archived_by_folder"),
    ]

    operations = []
