# Generated by Django 5.0.2 on 2026-04-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0012_assign_default_folders"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="snoozed_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
