# Generated by Django 5.0.2 on 2026-04-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0013_add_snoozed_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="archived_by_folder",
            field=models.BooleanField(default=False),
        ),
    ]
