# Generated by Django 5.0.2 on 2026-03-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={"ordering": ["-pinned", "-created_at"]},
        ),
        migrations.AddField(
            model_name="todo",
            name="pinned",
            field=models.BooleanField(default=False),
        ),
    ]
