# Generated by Django 5.0.2 on 2026-03-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_alter_todo_options_todo_pinned"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="todos/"),
        ),
    ]
