# Generated by Django 5.0.2 on 2026-03-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0004_todo_todos_user_id_4c2949_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="notes/"),
        ),
    ]
