# Generated by Django 5.0.2 on 2026-03-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0006_todo_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="color",
            field=models.CharField(default="default", max_length=20),
        ),
    ]
