# Generated by Django 5.0.2 on 2026-04-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_add_device_fingerprint"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deactivation_reason",
            field=models.CharField(
                blank=True,
                choices=[("self", "Self"), ("admin", "Admin")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="deletion_recovery_token",
            field=models.CharField(blank=True, db_index=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="reactivation_token",
            field=models.CharField(blank=True, db_index=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="reactivation_token_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="scheduled_deletion_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
